# druid
spring: 
  datasource: 
    url: jdbc:mysql://192.168.223.129:3306/daichao?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: nodeuser
    password: nodeuser123!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 4
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20